### ISSUE TITLE
Github检索问题

### ISSUE THREAD

**Issue by Samiya321** [ZeroX1ng/Sub-web-Surge#1]
你好 请问你是怎么检索到我的仓库脚本的
我好像已经把脚本分支切换到非默认了，按道理Github的搜索是搜索不出来的
想请教一下检索技巧hhh

**Comment by ZeroX1ng** [comment]
才看到大佬的留言。。说实话我忘了=w=  
感觉好像是搜索revenuecat那个js的时候有人引用过，然后我顺着用户名点过来看到的。。
但是我确实是第一个star的。。。如果介意那我取消一哈

**Comment by Samiya321** [comment]
没事没事 不介意Star啥的 引用注意一下来源就行
欢迎一起讨论
